# Generated by Django 5.0.1 on 2024-04-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_rename_faculty_semester_faculty_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Notes.faculty'),
            preserve_default=False,
        ),
    ]
